### ISSUE TITLE
I have problems running the Bot

### ISSUE THREAD

**Issue by SunySuperman** [capRS/wolves#1]
`Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\wolves-main\bot.py", line 47, in <module>
    rich_overnight()
  File "C:\Users\Administrator\Desktop\wolves-main\bot.py", line 38, in rich_overnight
    find_button()
  File "C:\Users\Administrator\Desktop\wolves-main\bot.py", line 30, in find_button
    if gui.pixel(coords[0], coords[1])[0] == 255:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pyscreeze\__init__.py", line 613, in pixel
    return (r, g, b)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 124, in __exit__
    next(self.gen)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pyscreeze\__init__.py", line 122, in __win32_openDC
    raise WindowsError("windll.user32.ReleaseDC failed : return 0")
OSError: windll.user32.ReleaseDC failed : return 0`

**Comment by capRS** [comment]
If you got this error, then you installed everything correctly, but the bot can not get the watch button color and click it.
This error is because you of one of this reason
 1. You are using python 3.9 - you need to use python 3.7
2. Your coordinates are not set right as I explained in this video, so the bot is checking else were and can't find the watch video button 

If you still can't solve it, pls contact me on discord, I will show you step by step
RedScorpion#5785

**Comment by salaamdev** [comment]
> `Traceback (most recent call last): File "C:\Users\Administrator\Desktop\wolves-main\bot.py", line 47, in <module> rich_overnight() File "C:\Users\Administrator\Desktop\wolves-main\bot.py", line 38, in rich_overnight find_button() File "C:\Users\Administrator\Desktop\wolves-main\bot.py", line 30, in find_button if gui.pixel(coords[0], coords[1])[0] == 255: File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pyscreeze\__init__.py", line 613, in pixel return (r, g, b) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 124, in __exit__ next(self.gen) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pyscreeze\__init__.py", line 122, in __win32_openDC raise WindowsError("windll.user32.ReleaseDC failed : return 0") OSError: windll.user32.ReleaseDC failed : return 0`

If you got this error, then you installed everything correctly, but the bot can not get the watch button color and click it.
This error is because you of one of this reason
 1. You are using python 3.9 - you need to use python 3.7
2. Your coordinates are not set right as I explained in this video, so the bot is checking else were and can't find the watch video button 

If you still can't solve, pls contact me on discord, i will show you step by step
